version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: mit8103_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./portfolio-1-database-design:/docker-entrypoint-initdb.d
    networks:
      - mit8103_network

  mongodb:
    image: mongo:6.0
    container_name: mit8103_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mit8103_network

volumes:
  postgres_data:
    driver: local
  mongo_data:
    driver: local

networks:
  mit8103_network:
    driver: bridge